const sampleListings = [
  {
    title: "Modern City Apartment",
    description: "Stay in the heart of the city with all modern amenities and skyline views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb" },
    price: 2000,
    location: "New York",
    country: "United States",
    geometry: { type: "Point", coordinates: [-74.006, 40.7128] },
    category: "Iconic cities",
  },
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage with stunning ocean views and private beach access.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2" },
    price: 1500,
    location: "Malibu",
    country: "United States",
    geometry: { type: "Point", coordinates: [-118.7798, 34.0259] },
    category: "Beach",
  },
  {
    title: "Rustic Mountain Cabin",
    description: "A cozy log cabin nestled in the mountains, perfect for hiking and stargazing.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1542718610-a1d656d1884c" },
    price: 1200,
    location: "Aspen",
    country: "United States",
    geometry: { type: "Point", coordinates: [-106.8175, 39.1911] },
    category: "Cabins",
  },
  {
    title: "Luxury Villa with Pool",
    description: "Experience ultimate luxury in this stunning villa with private pool and tropical garden.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1613977257363-707ba9348227" },
    price: 5000,
    location: "Bali",
    country: "Indonesia",
    geometry: { type: "Point", coordinates: [115.1889, -8.4095] },
    category: "Amazing pools",
  },
  {
    title: "Charming Paris Studio",
    description: "A romantic studio in the heart of Paris, walking distance from the Eiffel Tower.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267" },
    price: 1800,
    location: "Paris",
    country: "France",
    geometry: { type: "Point", coordinates: [2.3522, 48.8566] },
    category: "Iconic cities",
  },
  {
    title: "Lakeside Retreat",
    description: "Peaceful lakeside home with private dock, canoe, and breathtaking sunrise views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4" },
    price: 1600,
    location: "Lake Tahoe",
    country: "United States",
    geometry: { type: "Point", coordinates: [-120.0324, 38.9399] },
    category: "Lakefront",
  },
  {
    title: "Penthouse with City Views",
    description: "Luxurious penthouse on the 40th floor with panoramic views of the Dubai skyline.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf" },
    price: 7000,
    location: "Dubai",
    country: "UAE",
    geometry: { type: "Point", coordinates: [55.2708, 25.2048] },
    category: "Iconic cities",
  },
  {
    title: "Cozy Scottish Countryside Cottage",
    description: "A traditional stone cottage surrounded by rolling green hills and sheep pastures.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1518780664697-55e3ad937233" },
    price: 900,
    location: "Edinburgh",
    country: "Scotland",
    geometry: { type: "Point", coordinates: [-3.1883, 55.9533] },
    category: "Rooms",
  },
  {
    title: "Tropical Overwater Bungalow",
    description: "Sleep above crystal-clear turquoise waters in this iconic overwater bungalow.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1439066615861-d1af74d74000" },
    price: 8000,
    location: "Bora Bora",
    country: "French Polynesia",
    geometry: { type: "Point", coordinates: [-151.7415, -16.5004] },
    category: "OMG!",
  },
  {
    title: "Historic Townhouse in Rome",
    description: "Stay in a beautifully restored 18th-century townhouse near the Colosseum.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b" },
    price: 2200,
    location: "Rome",
    country: "Italy",
    geometry: { type: "Point", coordinates: [12.4964, 41.9028] },
    category: "Iconic cities",
  },
  {
    title: "Desert Glamping Tent",
    description: "A luxury glamping tent in the middle of the Sahara with private chef and starlit dinners.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4" },
    price: 3500,
    location: "Marrakech",
    country: "Morocco",
    geometry: { type: "Point", coordinates: [-7.9811, 31.6295] },
    category: "OMG!",
  },
  {
    title: "Scandinavian Forest Cabin",
    description: "A minimalist cabin deep in the Norwegian forest with a wood-burning sauna.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4" },
    price: 1300,
    location: "Bergen",
    country: "Norway",
    geometry: { type: "Point", coordinates: [5.3221, 60.3913] },
    category: "Cabins",
  },
  {
    title: "Santorini Cliffside Villa",
    description: "Iconic white-washed villa perched on the caldera cliffs with private infinity pool.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff" },
    price: 4500,
    location: "Santorini",
    country: "Greece",
    geometry: { type: "Point", coordinates: [25.4615, 36.3932] },
    category: "Amazing views",
  },
  {
    title: "Treehouse in the Rainforest",
    description: "A magical treehouse perched among the jungle canopy of Costa Rica with wildlife views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1448375240586-882707db888b" },
    price: 1100,
    location: "Manuel Antonio",
    country: "Costa Rica",
    geometry: { type: "Point", coordinates: [-84.1541, 9.3921] },
    category: "OMG!",
  },
  {
    title: "Brooklyn Loft",
    description: "Industrial-style loft in Brooklyn with exposed brick, high ceilings, and rooftop access.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688" },
    price: 1700,
    location: "Brooklyn",
    country: "United States",
    geometry: { type: "Point", coordinates: [-73.9442, 40.6782] },
    category: "Rooms",
  },
  {
    title: "Japanese Zen Ryokan",
    description: "Experience traditional Japanese hospitality in a serene ryokan with onsen hot spring.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1528360983277-13d401cdc186" },
    price: 2500,
    location: "Kyoto",
    country: "Japan",
    geometry: { type: "Point", coordinates: [135.7681, 35.0116] },
    category: "Rooms",
  },
  {
    title: "Safari Lodge",
    description: "Luxury tented lodge on the edge of the Serengeti with daily game drives included.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1516426122078-c23e76319801" },
    price: 6000,
    location: "Serengeti",
    country: "Tanzania",
    geometry: { type: "Point", coordinates: [34.8888, -2.3333] },
    category: "Amazing views",
  },
  {
    title: "Amsterdam Canal House",
    description: "A classic 17th-century canal house with original features and views of the canals.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017" },
    price: 2100,
    location: "Amsterdam",
    country: "Netherlands",
    geometry: { type: "Point", coordinates: [4.9041, 52.3676] },
    category: "Iconic cities",
  },
  {
    title: "Beachside Bungalow in Goa",
    description: "Laid-back beach bungalow steps from the Arabian Sea with hammock and beach shack vibes.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57" },
    price: 600,
    location: "Goa",
    country: "India",
    geometry: { type: "Point", coordinates: [74.124, 15.2993] },
    category: "Beach",
  },
  {
    title: "Cliffside House in Big Sur",
    description: "Dramatic cliffside home in Big Sur with floor-to-ceiling ocean views and hot tub.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1474690870753-1b92efa1f2d8" },
    price: 3800,
    location: "Big Sur",
    country: "United States",
    geometry: { type: "Point", coordinates: [-121.9022, 36.2704] },
    category: "Amazing views",
  },
  {
    title: "Converted Windmill",
    description: "A quirky and charming converted windmill in the Dutch countryside with 360° views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64" },
    price: 1400,
    location: "Rotterdam",
    country: "Netherlands",
    geometry: { type: "Point", coordinates: [4.4777, 51.9244] },
    category: "OMG!",
  },
  {
    title: "Beachfront Penthouse in Barcelona",
    description: "Stylish penthouse apartment on Barceloneta beach with terrace and sea views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2" },
    price: 3200,
    location: "Barcelona",
    country: "Spain",
    geometry: { type: "Point", coordinates: [2.1734, 41.3851] },
    category: "Beach",
  },
  {
    title: "Canadian Lakefront Chalet",
    description: "A cozy chalet on the shores of Muskoka Lakes, perfect for fishing and kayaking.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b" },
    price: 1900,
    location: "Muskoka",
    country: "Canada",
    geometry: { type: "Point", coordinates: [-79.3832, 45.0] },
    category: "Lakefront",
  },
  {
    title: "Vineyard Farmhouse in Tuscany",
    description: "A rustic farmhouse surrounded by vineyards and olive groves with wine cellar access.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1467003909585-2f8a72700288" },
    price: 2800,
    location: "Tuscany",
    country: "Italy",
    geometry: { type: "Point", coordinates: [11.2558, 43.7711] },
    category: "Farms",
  },
  {
    title: "Sydney Harbour Apartment",
    description: "Modern apartment with stunning views of the Sydney Opera House and Harbour Bridge.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9" },
    price: 3000,
    location: "Sydney",
    country: "Australia",
    geometry: { type: "Point", coordinates: [151.2093, -33.8688] },
    category: "Iconic cities",
  },
  {
    title: "Mountain Chalet in Swiss Alps",
    description: "Ski-in ski-out chalet in the heart of the Swiss Alps with fireplace and sauna.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1531310197839-ccf54634509e" },
    price: 5500,
    location: "Zermatt",
    country: "Switzerland",
    geometry: { type: "Point", coordinates: [7.7491, 46.0207] },
    category: "Amazing views",
  },
  {
    title: "Havana Colonial Mansion",
    description: "A grand colonial mansion in Old Havana with courtyard, vintage decor, and rooftop bar.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429" },
    price: 800,
    location: "Havana",
    country: "Cuba",
    geometry: { type: "Point", coordinates: [-82.3666, 23.1136] },
    category: "Iconic cities",
  },
  {
    title: "Converted Lighthouse",
    description: "A one-of-a-kind converted lighthouse on the Maine coast with panoramic sea views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21" },
    price: 2600,
    location: "Portland",
    country: "United States",
    geometry: { type: "Point", coordinates: [-70.2553, 43.6591] },
    category: "OMG!",
  },
  {
    title: "Boho Beach House in Tulum",
    description: "Stylish boho-chic beach house in Tulum with cenote access and jungle surroundings.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1596178060671-7a80dc8059ea" },
    price: 2400,
    location: "Tulum",
    country: "Mexico",
    geometry: { type: "Point", coordinates: [-87.4654, 20.2114] },
    category: "Beach",
  },
  {
    title: "Floating Houseboat in Kerala",
    description: "A traditional Kerala kettuvallam houseboat cruising the backwaters with all meals included.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1562602833-0f4ab2fc46e3" },
    price: 700,
    location: "Alleppey",
    country: "India",
    geometry: { type: "Point", coordinates: [76.3388, 9.4981] },
    category: "OMG!",
  },
  {
    title: "Cliffside Cave Hotel",
    description: "Sleep in a carved cave suite in Cappadocia with hot air balloon views at sunrise.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1523978591478-c753949ff840" },
    price: 1800,
    location: "Cappadocia",
    country: "Turkey",
    geometry: { type: "Point", coordinates: [34.8307, 38.6431] },
    category: "Amazing views",
  },
  {
    title: "Ski Chalet in Whistler",
    description: "A spacious ski chalet minutes from Whistler Blackcomb with hot tub and mountain views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1551524559-8af4e6624178" },
    price: 4200,
    location: "Whistler",
    country: "Canada",
    geometry: { type: "Point", coordinates: [-122.9574, 50.1163] },
    category: "Cabins",
  },
  {
    title: "Bangkok Rooftop Condo",
    description: "Sleek high-rise condo with infinity pool and rooftop access overlooking Bangkok's skyline.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1508009603885-50cf7c579365" },
    price: 1100,
    location: "Bangkok",
    country: "Thailand",
    geometry: { type: "Point", coordinates: [100.5018, 13.7563] },
    category: "Amazing pools",
  },
  {
    title: "Rio de Janeiro Favela Art Loft",
    description: "A vibrant art-filled loft in a curated Santa Teresa neighborhood with city and bay views.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325" },
    price: 950,
    location: "Rio de Janeiro",
    country: "Brazil",
    geometry: { type: "Point", coordinates: [-43.1729, -22.9068] },
    category: "Iconic cities",
  },
  {
    title: "Glass Igloo in Lapland",
    description: "Sleep under the Northern Lights in a heated glass igloo surrounded by Finnish snow forests.",
    image: { filename: "listingimage", url: "https://images.unsplash.com/photo-1548013146-72479768bada" },
    price: 4800,
    location: "Rovaniemi",
    country: "Finland",
    geometry: { type: "Point", coordinates: [25.7294, 66.5039] },
    category: "OMG!",
  },
];

module.exports = sampleListings;